services:
  - type: web
    name: telegram-bot
    env: python
    build:
      commands:
        - pip install -r requirements.txt
    start: python main.py
    healthCheckPath: /health
    port: 8080
